# Generated by Django 6.1 on 2026-09-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saleitem_total_alter_saleorder_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='category',
            field=models.CharField(choices=[('party', 'Праздник'), ('masterclass', 'Мастер-класс'), ('face_painting', 'Аквагрим'), ('cafe', 'Кафе'), ('toys', 'Игрушки'), ('entrance', 'Гости (входные билеты)')], max_length=20),
        ),
    ]
