# Generated by Django 6.1 on 2026-09-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказов'},
        ),
        migrations.AlterModelOptions(
            name='saleorder',
            options={'ordering': ['-date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=100, unique=True, verbose_name='ID чека')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_type', models.CharField(max_length=20, verbose_name='Способ оплаты')),
                ('guests_count', models.IntegerField(default=1, verbose_name='Гостей')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Сырые данные ОФД')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('processed', 'Обработан'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработан')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Чек ОФД',
                'verbose_name_plural': 'Чеки ОФД',
                'ordering': ['-created_at'],
            },
        ),
    ]
